from pathlib import Path
import os
import subprocess
import sys


# ==================== 启动配置区域 ====================
PROJECT_ROOT = Path(__file__).resolve().parents[2]

MODULE_ROOT = Path(__file__).resolve().parent
SCRIPT_PATH = MODULE_ROOT / "main.py"

DATA_FOLDER_NAME = "Gemma31b_bge"
DATABASE_NAME = "hug"
DEVICE = "cuda"

KG_FILENAME = "service_kg_multi.gpickle"
MODEL_FILENAME = "gnn1_rgcn_best.pth"
TRAIN_TASKS_FILENAME = "data.json"
SERVICE_FILENAME = "tool_desc.json"

EMBEDDING_URL = "http://127.0.0.1:11434/v1/embeddings"
EMBEDDING_MODEL = "mxbai-embed-large:latest"
EMBEDDING_TIMEOUT = "300"

USE_BEAM = True
BEAM_WIDTH = 5
USE_DYNAMIC_BEAM = False
BEAM_MIN = 1
BEAM_MAX = 10
BEAM_THRESHOLD_HIGH = 0.30
BEAM_THRESHOLD_LOW = 0.05
STEP1_SEMANTIC_KEEP_RATIO = 0.5
HISTORY_TOPK = 10
HISTORY_BONUS_STEP1 = 0.15
HISTORY_BONUS_LATER = 0.00
STRICT_NEIGHBOR_ONLY_AFTER_STEP1 = True

REQUIREMENT_TOPK = 24
REQUIREMENT_MIN_PLAN_SIZE = 2
REQUIREMENT_COVERAGE_THRESHOLD = 0.55
TREE_BUDGET_MULTIPLIER = 8
TREE_QUEUE_SIZE = 24
TREE_CHILDREN_PER_REQUIREMENT = 4
TREE_RELATION_KEEP = 1
TREE_MATCH_THRESHOLD = 0.05
TREE_MRG_PROB_THRESHOLD = 0.55
TREE_ALPHA_MATCH = 1.0
TREE_BETA_MRG = 1.0
TREE_ETA_HISTORY = 0.6
TREE_GAMMA_DEP = 0.4
TREE_RHO_REDUNDANCY = 0.25
TREE_FRONTIER_SCORE_THRESHOLD = 0.0
TREE_ENABLE_STATE_DOMINANCE = True
TREE_USE_DEP_SIG = True
MODULE4_TOP_K = 5
MODULE4_INCLUDE_M_MINUS_1 = True

SAVE_INTERVAL = 50
MAX_WORKERS = 4
TASK_TIMEOUT = 1800

TEST_DB_DIR = PROJECT_ROOT / "Data" / DATA_FOLDER_NAME / "test" / DATABASE_NAME
TRAIN_DB_DIR = PROJECT_ROOT / "Data" / DATA_FOLDER_NAME / "train" / DATABASE_NAME
INPUT_FILE = TEST_DB_DIR / "stage2_dag.json"
OUTPUT_FILE = TEST_DB_DIR / "stage3_tree_candidates.json"
UNFINISHED_FILE = TEST_DB_DIR / "unfinished_stage3_tree_candidates.json"
# =====================================================


def build_env() -> dict:
    env = os.environ.copy()
    env["MRG_SC_DATA_ROOT"] = str(PROJECT_ROOT / "Data" / DATA_FOLDER_NAME)
    env["MRG_SC_DATASET"] = DATABASE_NAME
    env["MRG_SC_DEVICE"] = DEVICE
    env["MRG_SC_EMBEDDING_URL"] = EMBEDDING_URL
    env["MRG_SC_EMBEDDING_MODEL"] = EMBEDDING_MODEL
    env["MRG_SC_EMBEDDING_TIMEOUT"] = EMBEDDING_TIMEOUT
    env["MRG_TREE_KG_PATH"] = str(TRAIN_DB_DIR / KG_FILENAME)
    env["MRG_TREE_MODEL_PATH"] = str(TRAIN_DB_DIR / MODEL_FILENAME)
    env["MRG_TREE_TRAIN_TASKS_FILE"] = str(TRAIN_DB_DIR / TRAIN_TASKS_FILENAME)
    env["MRG_TREE_SERVICE_FILE"] = str(TEST_DB_DIR / SERVICE_FILENAME)
    env["MRG_TREE_USE_BEAM"] = str(USE_BEAM)
    env["MRG_TREE_BEAM_WIDTH"] = str(BEAM_WIDTH)
    env["MRG_TREE_USE_DYNAMIC_BEAM"] = str(USE_DYNAMIC_BEAM)
    env["MRG_TREE_BEAM_MIN"] = str(BEAM_MIN)
    env["MRG_TREE_BEAM_MAX"] = str(BEAM_MAX)
    env["MRG_TREE_BEAM_THRESHOLD_HIGH"] = str(BEAM_THRESHOLD_HIGH)
    env["MRG_TREE_BEAM_THRESHOLD_LOW"] = str(BEAM_THRESHOLD_LOW)
    env["MRG_TREE_STEP1_SEMANTIC_KEEP_RATIO"] = str(STEP1_SEMANTIC_KEEP_RATIO)
    env["MRG_TREE_HISTORY_TOPK"] = str(HISTORY_TOPK)
    env["MRG_TREE_HISTORY_BONUS_STEP1"] = str(HISTORY_BONUS_STEP1)
    env["MRG_TREE_HISTORY_BONUS_LATER"] = str(HISTORY_BONUS_LATER)
    env["MRG_TREE_STRICT_NEIGHBOR_ONLY_AFTER_STEP1"] = str(STRICT_NEIGHBOR_ONLY_AFTER_STEP1)
    env["MRG_TREE_REQUIREMENT_TOPK"] = str(REQUIREMENT_TOPK)
    env["MRG_TREE_REQUIREMENT_MIN_PLAN_SIZE"] = str(REQUIREMENT_MIN_PLAN_SIZE)
    env["MRG_TREE_REQUIREMENT_COVERAGE_THRESHOLD"] = str(REQUIREMENT_COVERAGE_THRESHOLD)
    env["MRG_TREE_BUDGET_MULTIPLIER"] = str(TREE_BUDGET_MULTIPLIER)
    env["MRG_TREE_QUEUE_SIZE"] = str(TREE_QUEUE_SIZE)
    env["MRG_TREE_CHILDREN_PER_REQUIREMENT"] = str(TREE_CHILDREN_PER_REQUIREMENT)
    env["MRG_TREE_RELATION_KEEP"] = str(TREE_RELATION_KEEP)
    env["MRG_TREE_MATCH_THRESHOLD"] = str(TREE_MATCH_THRESHOLD)
    env["MRG_TREE_MRG_PROB_THRESHOLD"] = str(TREE_MRG_PROB_THRESHOLD)
    env["MRG_TREE_ALPHA_MATCH"] = str(TREE_ALPHA_MATCH)
    env["MRG_TREE_BETA_MRG"] = str(TREE_BETA_MRG)
    env["MRG_TREE_ETA_HISTORY"] = str(TREE_ETA_HISTORY)
    env["MRG_TREE_GAMMA_DEP"] = str(TREE_GAMMA_DEP)
    env["MRG_TREE_RHO_REDUNDANCY"] = str(TREE_RHO_REDUNDANCY)
    env["MRG_TREE_FRONTIER_SCORE_THRESHOLD"] = str(TREE_FRONTIER_SCORE_THRESHOLD)
    env["MRG_TREE_ENABLE_STATE_DOMINANCE"] = str(TREE_ENABLE_STATE_DOMINANCE)
    env["MRG_TREE_USE_DEP_SIG"] = str(TREE_USE_DEP_SIG)
    env["MRG_TREE_MODULE4_TOP_K"] = str(MODULE4_TOP_K)
    env["MRG_TREE_MODULE4_INCLUDE_M_MINUS_1"] = str(MODULE4_INCLUDE_M_MINUS_1)
    env["MRG_TREE_MODULE3_SAVE_INTERVAL"] = str(SAVE_INTERVAL)
    env["MRG_TREE_MODULE3_MAX_WORKERS"] = str(MAX_WORKERS)
    env["MRG_TREE_MODULE3_TASK_TIMEOUT"] = str(TASK_TIMEOUT)
    env["MRG_TREE_MODULE3_INPUT_FILE"] = str(INPUT_FILE)
    env["MRG_TREE_MODULE3_OUTPUT_FILE"] = str(OUTPUT_FILE)
    env["MRG_TREE_MODULE3_UNFINISHED_FILE"] = str(UNFINISHED_FILE)
    return env


def main() -> None:
    if not SCRIPT_PATH.exists():
        raise FileNotFoundError(f"Script not found: {SCRIPT_PATH}")

    env = build_env()
    print("=== MODULE 3: FRONTIER TREE SEARCH ===")
    print(f"PROJECT_ROOT     = {PROJECT_ROOT}")
    print(f"DATA_FOLDER_NAME = {DATA_FOLDER_NAME}")
    print(f"DATABASE_NAME    = {DATABASE_NAME}")
    print(f"TEST_DB_DIR      = {TEST_DB_DIR}")
    print(f"TRAIN_DB_DIR     = {TRAIN_DB_DIR}")
    print(f"INPUT_FILE       = {INPUT_FILE}")
    print(f"OUTPUT_FILE      = {OUTPUT_FILE}")
    print(f"UNFINISHED_FILE  = {UNFINISHED_FILE}")
    print(f"MAX_WORKERS      = {MAX_WORKERS}")
    print(f"SAVE_INTERVAL    = {SAVE_INTERVAL}")
    print(f"TASK_TIMEOUT     = {TASK_TIMEOUT}")
    print(f"DEVICE           = {DEVICE}")
    print(f"EMBEDDING_URL    = {EMBEDDING_URL}")
    print(f"EMBEDDING_MODEL  = {EMBEDDING_MODEL}")

    subprocess.run(
        [sys.executable, str(SCRIPT_PATH)],
        cwd=str(MODULE_ROOT),
        env=env,
        check=True,
    )


if __name__ == "__main__":
    main()
